### ISSUE TITLE
Why is the step_size = 4? What does it signify?

### ISSUE THREAD

**Issue by bankanikhil29** [Kyushik/Attention#1]
Does step_size denote time stamps?

Is it 'k' in this image: 
![Attention_for_Image_Caption](https://user-images.githubusercontent.com/36372078/60802190-00acc600-a196-11e9-8628-de7cb245ea79.png)

**Comment by Kyushik** [comment]
Oh, sorry for late reply. It is k in the image. At first I tried to apply the attention to sequential data like text or video. However, I applied it to MNIST data, which is not sequential. So it operates RNN calculation 4 times with same image. For MNIST, it is not a problem that k set to 1.

**Comment by bankanikhil29** [comment]
Thank you so much. I tried training this model with step size = 1. It gave almost similar performance.
Here is the saved network if anyone requires.
[saved_networks1_stepsize_1.zip](https://github.com/Kyushik/Attention/files/3385328/saved_networks1_stepsize_1.zip)
